export const feedConstants = {

    GLOBAL_FEEDS_REQUEST: 'GLOBAL_FEEDS_REQUEST',
    GLOBAL_FEEDS_SUCCESS: 'GLOBAL_FEEDS_SUCCESS',
    GLOBAL_FEEDS_FAILURE: 'GLOBAL_FEEDS_FAILURE',
    USER_FEEDS_REQUEST: 'USER_FEEDS_REQUEST',
    USER_FEEDS_SUCCESS: 'USER_FEEDS_SUCCESS',
    USER_FEEDS_FAILURE: 'USER_FEEDS_FAILURE',
    SINGLE_FEED_REQUEST: 'SINGLE_FEED_REQUEST',
    SINGLE_FEED_SUCCESS: 'SINGLE_FEED_SUCCESS',
    SINGLE_FEED_ERROR: 'SINGLE_FEED_ERROR',

    TAGS_REQUEST: 'TAGS_REQUEST',
    TAGS_SUCCESS: 'TAGS_SUCCESS',
    TAGS_FAILURE: 'TAGS_FAILURE',

    CREATE_ARTICLE_REQUEST: 'CREATE_ARTICLE_REQUEST',
    CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
    CREATE_ARTICLE_FAILURE: 'CREATE_ARTICLE_FAILURE',

    DELETE_ARTICLE_REQUEST: 'DELETE_ARTICLE_REQUEST',
    DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
    DELETE_ARTICLE_ERROR: 'DELETE_ARTICLE_ERROR',

    FETCH_COMMENTS_REQUEST: 'FETCH_COMMENTS_REQUEST',
    FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
    FETCH_COMMENTS_ERROR: 'FETCH_COMMENTS_ERROR',

    POST_COMMENT_REQUEST: 'POST_COMMENT_REQUEST',
    POST_COMMENT_SUCCESS: 'POST_COMMENT_SUCCESS',
    POST_COMMENT_FAILURE: 'POST_COMMENT_FAILURE',

    DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
    DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_ERROR: 'DELETE_COMMENT_ERROR',
};
