export const API_URL = 'https://conduit.productionready.io/api/';

export const userConstants = {

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    SET_LOGIN_USER: 'SET_LOGIN_USER',

    SENDING_REQUEST: 'SENDING_REQUEST',
    REQUEST_ERROR: 'REQUEST_ERROR',

    LOGOUT: 'LOGOUT'
};
