export const API_URL = 'https://conduit.productionready.io/api/';

export const userConstants = {

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    SET_LOGIN_USER: 'SET_LOGIN_USER',

    SENDING_REQUEST: 'SENDING_REQUEST',
    REQUEST_ERROR: 'REQUEST_ERROR',

    LOGOUT: 'LOGOUT',

    FETCH_PROFILE_REQUEST: 'FETCH_PROFILE_REQUEST',
    FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
    FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',

    FOLLOW_USER_REQUEST: 'FOLLOW_USER_REQUEST',
    FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
    FOLLOW_USER_FAILURE: 'FOLLOW_USER_FAILURE',
};
